# Should national sports leagues look beyond their boards for profits?  {#To-expand,-or-not-to-expand?}

#### Keywords {International expansion, NFL, NHL, MLB, NBA, Serie A, La Liga, English Premier League, EPL,}

## Professional sport leagues are racing to expand from their traditional markets, should they?  {#Defining-success-and-failure.}

Sports leagues are money making machines as evidenced by the increase in franchise values estimated by Forbes.  The goal of any profit seeking venture is to grow as fast as possible in the short-term without sacrificing long-term profitability.  As leagues look for faster growth, they naturally look to external markets to increase their potential market size.  A brief look back in time shows a list of international expansion failures including the NFL withdrawing from the European continent with their development league, Formula 1 entering and exiting the US market on a semi-regular basis, MLB sporadically playing games outside the us in 1996, '99, 2000, '04, '08, '12, '14.  Were any of these exercises profitable, and if so, what are the factors that lead to a successful expansing?

There are pockets of success which we can use to benchmark for example how soccer became such a huge international sport.  Similarly, cricket is also an extremely international sport with some variations (Twenty20) in the games rules allowing for faster pace of play to attract even larger audiences.  

Domestic Sports leagues are currently trying multiple ways to expand internationally to monetize their product (broadcast rights, merchandise, tickets, brand).  Some attempt to play off-season events in faraway lands (e.g., the National Basketball League ("NBA"), domestic soccer league soccer friendlies).  Others tried to build development leagues in new markets (e.g., the NFL with the European Development League).  Finally, some leagues are putting real, meaningful games outside their home markets (e.g., Major League Baseball ("MLB") in South America and the National Hockey League ("NHL") and NFL targeting Sweden and the UK respectively.

The purpose of this Big Idea is to understand what defines success and to build a model which can predict, based on an international market structure, what strategies a league should pursue to be successful.  Specifically, we are trying to identify key success criteria by sport to maximize their chance of profitable expansion given a market structure of their target market.

## What market characteristics are most encouraging to achieve to profitable market expansion.  {#The-look-of-success.}

The right way to describe the problem is to is to understand what market dynamics (political, economic, social construction) make internal expansion more likely to succeed and attempt to predict the best actions or activities of leagues to maximize the potential for a positive outcome.  

Looking at the behavior of professional domestic league decision making, we will explore markets where Professional leagues have tried and failed (NFL development league in Europe and subsequently Germany), ongoing experiments in two classes:  (1) meaningful games defined as games being played with impact on league standings (e.g., MLB, NFL, NHL) and (2) off-season games defined as games played with no impact on league standings (e.g., NBA, European national soccer league friendlies).  Within these categories we will attempt to capture performance results through a variety of data sets including attendance at live events, merchandise sales outside domestic markets, international television rights valuation over time, international club membership where such official clubs exist.  The analysis will ignore the investments needed to achieve any results assuming leagues behave in as rational profit seeking entities over the long-term. Instead, we will design an experiment to predict success or failure given the target market across a variety of market expansion strategies.

To define market conditions will will explore the target expansion market across a variety of social, economic and political data sets.  

Looking at the social infrastructure we will concentrate on:
1.  Population growth and size of a defined target market (e.g., age, sex), and
2.  Existing local sporting enthusiasms based on available market data similar to above criteria (e.g., TV licensing, merchandise sales, sport club enrollments, estimate population of to be defined criteria of being a "sports fan").  

Economic data will perhaps be the most readily available from international sources including:
1.  Gross Domestic Product, Disposable Income,
2.  A to-be defined middle-class identification, and
3.  population growth.  

Finally, we will attempt to find viable public data on the political environment as it relates to foreign company acceptance through a variety of means including:
1.  Understanding trade surplus or deficit,
2.  Non-sport product introduction success / failure,
3.  Stability of government, political system, or
4.  General tolerance for international corporate entities.

Other data points we will consider are the correlation between the national market and international expansion target market looking at number and percentage of target market players in the league which could be a barometer for youth junior program success, junior programs in target market, time zone difference between national and international target market.  

With this information, the aim is to build a predictive model of strategy options for leagues to maximize their expected profitability.

## What is success and who will win? {#Predicting-success-criteria-and-strategies.}.

There are a lot of strategies tried and still in play.  From the available data which to this point is predominantly in my head, we believe the following leagues in their respective markets will be successful:  NHL in Europe and Eastern Asia and MLB in South America.  The drivers of our predictive model that highlight these two leagues as having success is the existing target market influence of baseball and hockey respectively and the number of players already successful in the national league.  The NHL will have a significant challenge similar to that faced by the NFLs expansion into London with the large time zones and distance teams need to cross for games and the corresponding impact on live game viewing opportunities to monetize through broadcast rights.  However, our model predicts the leagues can compensate these challenges building on the established fan base the sport has in market.  Core to all league success projections is the establishment of an existing middle class and underlying population interest in sports as we defined.  

One limitation of the analysis is the assumption that teams and/or leagues work in isolation.  With services like SportsCenter, it seems plausible that an expansion of viewership on T.V. of one sport could complement another, but with something like game attendance, where a fan has limited resources for tickets, they may be replacements.  Leagues are not working in isolation, so their interactions with one another might introduce new expansion approaches not covered in the current analysis.

Given the positive results of our predictive algorithm, we see immediate applications for identifying expansion markets for national sports leagues and hope to extend the logic to other commercial business or product expansion opportunity identification experiments.  
