---
title: "W201 Portfolio"
author: "Mark Barnett"
date: "MIDS Spring 2018"
site: bookdown::bookdown_site
documentclass: book
bibliography: references.bib
link-citations: yes
biblio-style: apalike
---

<!-- This won't be displayed but it will initialize your R session. Add any R libraries you need here. -->
```{r init,include=FALSE,echo=FALSE}
library(magrittr)
readLines('https://www.zotero.org/api/users/4684940/items/top?limit=25&format=bibtex&key=dZhBqI1K8eR2pdN7PGz5UGVk&v=1') %>% writeLines('references.bib')
```


# Welcome! {-}

Welcome to my portfolio

### Identifing success criteria and Market Expansion Strategies for Sports Leages to Win in Foreign Markets  {#Sports-Leagues-Expansion-Success-Prediction}

Looking for underlying market conditions and the behaoviors of sports leages to identify successful strategies to expanding into foreign markets. 

### Predicting the hatch timing of Mayflies {#Fly-Fishing-Match-the-Hatch-Prediction}

Identfy through weather patterns over a 12 month cycle the conditions to provide for accurate forecast of Mayfly hatches.  For use by travel planners, guides and fly shops for trip planning and sales recommendations, and for the individual fly fisherman/women to know what flies to bring on the water. 
  

## About the author {-}

Mark is a human, he has a spouse and two offspring all of whom are also human.  

*Updated: `r Sys.Date()`*
